package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'A'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("A")) {
    expectSteps {
        script {
            name = "nameptch13"
            scriptContent = "ptch3001"
        }
        script {
            name = "nameptch12 (1)"
            scriptContent = "ptch3001"
        }
        script {
            name = "nameptch12"
            scriptContent = "ptch3002"
        }
        script {
            scriptContent = "echo acds"
        }
        script {
            scriptContent = "sss"
        }
        script {
            name = "nameptch"
            scriptContent = "ptch3"
            formatStderrAsError = true
        }
        script {
            name = "nameptch3"
            scriptContent = "ptch3"
            formatStderrAsError = true
        }
        script {
            name = "nameptch5"
            scriptContent = "ptch3"
            formatStderrAsError = true
        }
        script {
            scriptContent = "ыы"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = "ptch3002"
        }
    }
}
